const express = require('express');
const path = require('path');
const app = express();

// Set EJS as the view engine
app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, '../views')); // Path to the 'views' directory

// Serve static files from the root directory
app.use(express.static(path.join(__dirname, '..'))); // Serve files from the root directory

app.use('/bundles', express.static(path.join(__dirname, '../bundles')));
app.use('/deskmats', express.static(path.join(__dirname, '../deskmats')));
app.use('/deals', express.static(path.join(__dirname, '../other')))
app.use('/keycaps', express.static(path.join(__dirname, '../bundles')));
app.use('/privacy-policy', express.static(path.join(__dirname, '../deskmats')));
app.use('/refund-policy', express.static(path.join(__dirname, '../other')))
app.use('/terms-of-service', express.static(path.join(__dirname, '../bundles')));
app.use('/keyboards', express.static(path.join(__dirname, '../deskmats')));

// Route to dynamically render a small portion of the page
app.get('/dynamic-content', (req, res) => {
    const data = {
        message: 'This content is dynamically generated by the server!',
        timestamp: new Date().toLocaleTimeString()
    };
    res.render('dynamic-part', { data }); // Render the EJS template with data
});

// Route for the root URL
app.get('/', (req, res) => {
    res.sendFile(path.join(__dirname, '../index.html')); // Serve the root index.html
});

// Start the server
const PORT = 3000;
app.listen(PORT, () => {
    console.log(`Server running on http://localhost:${PORT}`);
});